hooks:
  plan:
    pre:
      - type: run
        cmd: ['echo', 'Pre-plan hook started']
      - type: run
        cmd: ['mkdir', '-p', '/tmp/tf_cache_dir']
      - type: run
        cmd: ['ls', '-la', '/tmp']
      - type: run
        cmd: ['aws', 's3', 'sync', 's3://terraform-terratream-cache', '/tmp/tf_cache_dir']
    post:
      - type: run
        cmd: ['echo', 'Post-plan hook started']
      - type: run
        cmd: ['ls', '-la', '/tmp/tf_cache_dir']
      - type: run
        cmd: ['aws', 's3', 'sync', '/tmp/tf_cache_dir', 's3://terraform-terratream-cache']
